### ISSUE TITLE
Rust monster parse error

### ISSUE THREAD

**Issue by mmealman** [lhayhurst/TokenLab#14]
The XML output for the rust monster is throw a java error on the token output. Likely a result of some issue parsing the XML. XMl file can be downloaded from http://tarsis.org/me/rustmonster.zip

**Comment by lhayhurst** [comment]
fixed and released.  

the issue was the damage dice text.  it was "Rust."  (instead of 1d6 or whatever.)  I added a check to bounce on the regex "^[a-zA-Z]+$".
