### ISSUE TITLE
Attack roll bug, plus minor crit issue

### ISSUE THREAD

**Issue by mmealman** [lhayhurst/TokenLab#15]
Test character is http://tarsis.org/me/danzier.zip

I was initially testing crit rolls with this character. The crit chance roll(18-20 on rapier, 20 on dagger) are working fine, however the crit multiplier on the dagger(x3) is only rolling 1 extra die on the crit. A bit of logic to auto-roll the extra dice for a x3, x4, x5 crit would be nice, though it's not game breaking.

One issue I didn't expect though is the attack bonus is off for this character on import into Maptools. In Hero Lab he's dual wielding the rapier/dagger and getting a -1 attack bonus on each. However in maptool's after the import he's getting a +1 to hit bonus with each.

The XML output from Hero Lab is as expected:

```
<weapon name="Dagger, Punching" categorytext="Melee Weapon" typetext="P" attack="-1" damage="1d4" crit="20/x3" equipped="offhand" quantity="1">

<weapon name="Rapier" categorytext="Melee Weapon" typetext="P" attack="-1" damage="1d6+1" crit="18-20/x2" equipped="mainhand" quantity="1">
```

**Comment by lhayhurst** [comment]
this is fixed and released

**Comment by mmealman** [comment]
The crit component of this was fixed, but are you sure the -1 attack bonus issue was?

It still looks like it's rolling +1 on the attack rolls for the dagger and rapier on this character.

**Comment by lhayhurst** [comment]
right you are, doh!  re-opening

**Comment by lhayhurst** [comment]
Ok, the -1 should be fixed now.  I was assuming blithely that all attack modifiers would be positive!
