### ISSUE TITLE
Crits not rerolling

### ISSUE THREAD

**Issue by Bobsson** [lhayhurst/TokenLab#22]
Critical hits are using the original attack roll as the confirmation roll.  They also roll it each time for x3 and x4 weapons.

**Comment by lhayhurst** [comment]
Hi Bobsson!  Thanks for filing a bug!

For the original attack as the confirmation role - can you shoot me a screenshot (email it if that is easier, sozinsky at gmail dot com) of an example?  Here's a crit I just rolled:

[image](http://www.flickr.com/photos/45217036@N00/7633935390/)

Here my guy rolled a crit (17 on his +5 keen adamantine curved blade), hit on the first for 1d10+26, and then rolled to confirm, rolled a 60 on the attack role (he's a lvl 20 fighter), confirmed, and got the 1d10+26 again, for a total of 2d10+52.

Sound right? 

Thanks again for submitting!!

**Comment by lhayhurst** [comment]
Ok, I understand the bug now.  It's been fixed and rolled out with 0.21.  Thank you!
