### ISSUE TITLE
Suggestion:  suggestions for token names

### ISSUE THREAD

**Issue by dgroo** [lhayhurst/TokenLab#7]
Random thought - it might be good to have it just default token names to something like the hero name with whitespace replaced by underscores, or camel-cased or something.

**Comment by lhayhurst** [comment]
Good idea. will do it.

**Comment by dgroo** [comment]
As a note - this could also help with the Mac not having a naming field problem.  (Which I may try to look at later if I have a T-Day break.)

**Comment by dgroo** [comment]
Think I've got this covered with my recent check-in.  Will probably extend with upcoming work.
